### ISSUE TITLE
Prepackaged distributions are not accessible anymore

### ISSUE THREAD

**Issue by bfontaine** [Gant/Gant#3]
Since Codehaus is now down, all the prepackaged distributions are dead links on [your website](https://gant.github.io/Prepackaged_Distributions.html). [Homebrew](http://brew.sh/) relied on the 1.9.11 distribution URL, so it doesn’t work anymore. Is there any way you could re-host these distributions somewhere? You could try [GitHub releases](https://github.com/blog/1547-release-your-software).

Thanks!

**Comment by russel** [comment]
Sorry I failed to even note these issues, long story. Is this still an issue for you? It seems likely that there will be a 1.9.12 release and this has to lead to a sorting out of the location of the artefacts and distributables. Also an update of the packages.

**Comment by bfontaine** [comment]
[We removed `gant` from Homebrew](https://github.com/Homebrew/homebrew-boneyard/commit/e6212dc) because of that so it’s not an issue anymore for us.

**Comment by russel** [comment]
OK, sorry for the hassle.
