### ISSUE TITLE
gant website issues

### ISSUE THREAD

**Issue by tkruse** [Gant/Gant#4]
https://gant.github.io/
- Ugly blue box at to, looks like css error
- dist download hosted at codehaus not working anymore
- several unreachable sidbar items (links not clickable), liek "Getting gant"
- dead links in sidebar:
  -  https://gant.github.io/Clean_Target%20Set.html
  - https://gant.github.io/Maven_Target%20Set.html

**Comment by russel** [comment]
Apologies for completely missing this raised issue. It is clearly still a problem, and is a CSS error. There will be a 1.9.12 release in all likelihood so many of these issues will be addressed. Pull requests always gratefully received!

**Comment by corbym** [comment]
The dist download host is still not working.

**Comment by blackorzar** [comment]
The site downloads list dist up to groovy 2.3, but i am unsure if i should download it for groovy 2.4

**Comment by russel** [comment]
I'll see if I can get this fixed over the coming weekend. Everything should work fine with Groovy 2.4 as is, but if it doesn't then a new release will have to be done.

**Comment by russel** [comment]
Obviously I failed to get to this as I had hoped. Creating a new Gant release is now properly on the agenda.

**Comment by russel** [comment]
In the middle of making a release. Web pages issues now part of that, so I am closing this issue.
